"use client";

import { useRef, useState } from "react";
import { ArrowDown, BookmarkPlus, Download, FlipHorizontal2, FlipVertical2, Link2, Palette, RotateCcw, RotateCw, Trash2, Unlink2, Upload } from "lucide-react";
import { toast } from "sonner";
import { ColorField, Choice, IconButton, RangeField, Toggle } from "./editor-controls";
import type { Asset, Settings, ToolId } from "@/lib/editor-types";
import { colorCSS, colorRGBA, download } from "@/lib/image-editor";

export type AdjustmentProps = {
  asset?: Asset; settings: Settings; tool: ToolId; patch: (value: Partial<Settings>) => void;
  picking: string | null; pick: (field: "source" | "target" | "removeColor") => void;
  mask: boolean; setMask: (v: boolean) => void; reset: () => void;
  saved: string[]; saveColor: (value: string) => void; removeColor: (value: string) => void;
  setSavedColors: (colors: string[]) => void;
};

export default function Adjustments({ asset, settings: s, tool, patch, picking, pick, mask, setMask, reset, saved, saveColor, removeColor, setSavedColors }: AdjustmentProps) {
  const [newColor, setNewColor] = useState("");
  const paletteInput = useRef<HTMLInputElement>(null);
  const heading = { colors: "Ajustes de cor", alpha: "Transparência", size: "Tamanho e margens", transform: "Transformar imagem", palette: "Cores salvas" };
  const panelHeading = <div className="panel-heading"><h2>{heading[tool]}</h2><IconButton label="Restaurar ajustes" onClick={reset} disabled={!asset}><RotateCcw size={16} /></IconButton></div>;
  if (tool === "palette") return <>{panelHeading}<div className="control-section"><ColorField label="Nova cor da paleta" value={newColor} onChange={setNewColor} /><button className="button secondary wide" onClick={() => { saveColor(newColor); if (colorRGBA(newColor)) setNewColor(""); }} disabled={!colorRGBA(newColor)}><BookmarkPlus size={16} />Salvar cor</button></div><div className="control-section"><div className="section-heading palette-heading"><h3>Minha paleta <span className="count">{saved.length}</span></h3><IconButton label="Importar paleta JSON" onClick={() => paletteInput.current?.click()}><Upload size={16} /></IconButton><IconButton label="Exportar paleta JSON" disabled={!saved.length} onClick={() => download(new Blob([JSON.stringify({ version: 1, colors: saved }, null, 2)], { type: "application/json" }), "minha-paleta.json")}><Download size={16} /></IconButton></div><input ref={paletteInput} type="file" accept=".json,application/json" hidden onChange={async e => {
      const file = e.target.files?.[0]; e.target.value = ""; if (!file) return;
      try { if (file.size > 100_000) throw new Error(); const parsed: unknown = JSON.parse(await file.text());
        const list = parsed && typeof parsed === "object" && "colors" in parsed ? (parsed as { colors: unknown }).colors : parsed;
        if (!Array.isArray(list) || list.length > 40 || !list.every(c => typeof c === "string" && colorRGBA(c))) throw new Error();
        setSavedColors([...new Set([...saved, ...list])].slice(-40)); toast.success("Paleta importada.");
      } catch { toast.error("Paleta inválida. Use um JSON com até 40 cores válidas."); }
    }} />{saved.length ? <div className="saved-colors">{saved.map(c => <div className="saved-color-row" key={c}><button className="saved-color-use" disabled={!asset} onClick={() => { patch({ target: c, mode: s.mode === "none" ? "replace" : s.mode }); toast.success("Cor aplicada ao ícone atual."); }} aria-label={`Aplicar ${c}`}><span className="swatch" style={{ background: colorCSS(c) }} /><code>{c}</code></button><IconButton label={`Excluir cor ${c}`} onClick={() => removeColor(c)}><Trash2 size={15} /></IconButton></div>)}</div> : <div className="palette-empty"><Palette size={30} strokeWidth={1.2} /><span>Nenhuma cor salva</span></div>}</div></>;
  if (tool === "alpha") return <>{panelHeading}<fieldset className="controls-body" disabled={!asset}><section className="control-section"><h3>Remoção por cor</h3><Toggle label="Remover uma cor" checked={s.removeEnabled} onChange={removeEnabled => patch({ removeEnabled })} /><ColorField label="Cor a remover" value={s.removeColor} onChange={removeColor => patch({ removeColor })} onPick={() => pick("removeColor")} active={picking === "removeColor"} /><RangeField label="Similaridade" value={s.removeTolerance} onChange={removeTolerance => patch({ removeTolerance })} /><Toggle label="Somente áreas ligadas às bordas" checked={s.edgeOnly} onChange={edgeOnly => patch({ edgeOnly })} /></section><section className="control-section"><h3>Opacidade e fundo</h3><RangeField label="Opacidade do ícone" value={s.opacity} onChange={opacity => patch({ opacity })} /><Toggle label="Adicionar fundo" checked={s.backgroundEnabled} onChange={backgroundEnabled => patch({ backgroundEnabled })} />{s.backgroundEnabled && <ColorField label="Cor do fundo" value={s.background} onChange={background => patch({ background })} />}</section></fieldset></>;
  if (tool === "size") return <>{panelHeading}<fieldset className="controls-body" disabled={!asset}><section className="control-section"><h3>Dimensões da imagem</h3><Toggle label="Redimensionar" checked={s.resizeEnabled} onChange={resizeEnabled => patch({ resizeEnabled })} /><div className="dimensions"><div className="field"><label htmlFor="image-width">Largura</label><div className="dimension-input"><input id="image-width" type="number" min={1} max={8192} value={s.width} disabled={!s.resizeEnabled} onChange={e => { const width = Math.max(1, Math.min(8192, Number(e.target.value))); patch({ width, ...(s.lockRatio && asset ? { height: Math.max(1, Math.round(width * asset.height / asset.width)) } : {}) }); }} /><span>px</span></div></div><IconButton label={s.lockRatio ? "Desvincular proporções" : "Manter proporções"} aria-pressed={s.lockRatio} onClick={() => patch({ lockRatio: !s.lockRatio })}>{s.lockRatio ? <Link2 size={17} /> : <Unlink2 size={17} />}</IconButton><div className="field"><label htmlFor="image-height">Altura</label><div className="dimension-input"><input id="image-height" type="number" min={1} max={8192} value={s.height} disabled={!s.resizeEnabled} onChange={e => { const height = Math.max(1, Math.min(8192, Number(e.target.value))); patch({ height, ...(s.lockRatio && asset ? { width: Math.max(1, Math.round(height * asset.width / asset.height)) } : {}) }); }} /><span>px</span></div></div></div><Choice label="Dimensão rápida" value="custom" onChange={n => { const width = Number(n); patch({ resizeEnabled: true, width, height: s.lockRatio && asset ? Math.max(1, Math.round(width * asset.height / asset.width)) : width }); }} options={[{ value: "custom", label: "Personalizada" }, ...[16, 24, 32, 48, 64, 128, 256, 512, 1024].map(n => ({ value: String(n), label: `Largura de ${n} px` }))]} /></section><section className="control-section"><h3>Área ao redor do ícone</h3><Toggle label="Recortar margens transparentes" checked={s.trim} onChange={trim => patch({ trim })} /><RangeField label="Margem externa" value={s.padding} min={0} max={512} unit="px" onChange={padding => patch({ padding })} /></section></fieldset></>;
  if (tool === "transform") return <>{panelHeading}<fieldset className="controls-body" disabled={!asset}><section className="control-section"><h3>Orientação</h3><div className="transform-actions"><IconButton label="Girar 90 graus para a esquerda" onClick={() => patch({ rotation: (s.rotation + 270) % 360 })}><RotateCcw size={21} /></IconButton><output>{s.rotation}°</output><IconButton label="Girar 90 graus para a direita" onClick={() => patch({ rotation: (s.rotation + 90) % 360 })}><RotateCw size={21} /></IconButton></div><div className="transform-actions mirror-actions"><IconButton label="Espelhar horizontalmente" aria-pressed={s.flipX} onClick={() => patch({ flipX: !s.flipX })}><FlipHorizontal2 size={22} /></IconButton><IconButton label="Espelhar verticalmente" aria-pressed={s.flipY} onClick={() => patch({ flipY: !s.flipY })}><FlipVertical2 size={22} /></IconButton></div></section><section className="control-section"><Choice label="Ajuste de cores" value={s.filter} onChange={filter => patch({ filter: filter as Settings["filter"] })} options={[{ value: "none", label: "Sem filtro" }, { value: "grayscale", label: "Escala de cinza" }, { value: "invert", label: "Inverter cores" }]} /></section></fieldset></>;
  return <><div className="panel-heading"><h2>Ajustes de cor</h2><IconButton label="Restaurar ajustes" onClick={reset} disabled={!asset}><RotateCcw size={16} /></IconButton></div>
    <fieldset disabled={!asset} className="controls-body"><section className="control-section">
      <Choice label="Aplicação" value={s.mode} onChange={mode => patch({ mode: mode as Settings["mode"] })} options={[{ value: "replace", label: "Substituir uma cor" }, { value: "solid", label: "Recolorir todo o ícone" }, { value: "none", label: "Manter cores originais" }]} />
      {s.mode === "replace" && <ColorField label="Cor original" value={s.source} onChange={source => patch({ source })} onPick={() => pick("source")} active={picking === "source"} />}
      {s.mode !== "none" && <><div className="color-direction"><ArrowDown size={15} /></div><ColorField label="Nova cor" value={s.target} onChange={target => patch({ target })} onPick={() => pick("target")} active={picking === "target"} />
        <button className="text-action" onClick={() => saveColor(s.target)} disabled={!s.target}><BookmarkPlus size={15} /> Salvar esta cor</button></>}
      {saved.length > 0 && <div className="swatch-list">{saved.map(c => <button key={c} title={c} aria-label={`Usar ${c}`} className="swatch" style={{ background: colorCSS(c) }} onClick={() => patch({ target: c })} />)}</div>}
    </section>
    {s.mode === "replace" && <section className="control-section"><h3>Precisão da seleção</h3><RangeField label="Similaridade" value={s.tolerance} onChange={tolerance => patch({ tolerance })} /><Toggle label="Suavizar bordas" checked={s.smooth} onChange={smooth => patch({ smooth })} />{s.smooth && <RangeField label="Raio de suavização" value={s.radius} min={1} max={20} unit="px" onChange={radius => patch({ radius })} />}</section>}
    <section className="control-section"><h3>Revisão</h3><Toggle label="Mostrar máscara de alterações" checked={mask} onChange={setMask} />
      {asset && asset.colors.length > 0 && <><span className="section-label">Cores no original</span><div className="swatch-list">{asset.colors.map(c => <button key={c} className="swatch" style={{ background: colorCSS(c) }} title={c} aria-label={`Selecionar cor original ${c}`} onClick={() => patch({ source: c })} />)}</div></>}
    </section></fieldset>
  </>;
}
